CREATE SCHEMA IF NOT EXISTS PARKING_LOT;
USE PARKING_LOT;

CREATE TABLE PARKING_LOT
    (	Lot_name	VARCHAR(10)	NOT NULL,
		Camera_id	CHAR(5)		NOT NULL,
		Street		VARCHAR(20)	NOT NULL,
		City		VARCHAR(20)	NOT NULL,
		Zip_code	CHAR(5)		NOT NULL,
    	PRIMARY KEY (Camera_id));

/* STORES COORDINATE VALUES SEPARATELY*/
	/*
	INSERT INTO COORD_POSITION (x_position, y_position) VALUES( , )
	*/
CREATE TABLE COORD_POSITION
	(	Point_id	INT(10) 	NOT NULL AUTO_INCREMENT,
		x_position	DOUBLE DEFAULT 0,
		y_position	DOUBLE DEFAULT 0,
		PRIMARY KEY (Point_id)
	) ENGINE=INNODB;

CREATE TABLE PARKING_SPACE
    (	Point_id	INT(10) 	NOT NULL AUTO_INCREMENT,
    	Width		DECIMAL(10,2),
    	Height		DECIMAL(10.2),
		PRIMARY KEY (Point_id),
		FOREIGN KEY (Point_id)	REFERENCES COORD_POSITION(Point_id)
	) ENGINE=INNODB;

CREATE TABLE VEHICLE
    (	Point_id	INT(10) NOT NULL AUTO_INCREMENT,
		Parked_timestamp	TIMESTAMP,
		Vacated_timestamp	TIMESTAMP,
		Vehicle_type		VARCHAR(20) NOT NULL,
		PRIMARY KEY (Point_id),
		FOREIGN KEY (Point_id)	REFERENCES COORD_POSITION(Point_id));